### ISSUE TITLE
ollama config: Does it still require the port settings?

### ISSUE THREAD

**Issue by pmirla** [jaypyles/FreeAskInternet-API#3]
services:
  backend:
    image: jpyles0524/freeaskinternetapi:latest
    build:
      context: .
    container_name: searchbackend
    environment:
      - OLLAMA_HOST=http://ollama:11434 << should this be replaced with localhost?
    ports:
       - 8000:8000
    depends_on:
      - llm-freegpt35
    restart: on-failure
    networks:
      - search

With this>> 
I see an error.
 curl -X POST "http://localhost:8000/v1/chat/completions" \
     -H "Content-Type: application/json" \
     -d '{
           "model": "ollama",
           "messages": [{"role": "user", "content": "Why does the moon create the tides"}], "ollama_model":"llama3"
         }'

data: {"model":"ollama","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}

curl: (18) transfer closed with outstanding read data remaining

**Comment by jaypyles** [comment]
If you are not running a service in Docker, yes, you will need to expose the ports of Ollama and swap out the url to localhost, as you will be connecting over the host network, and not the Docker network.

**Comment by pmirla** [comment]
Thanks
